# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
